services:
  - type: web
    name: license-plate-prime-finder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn simple_finder:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
